import './globals.css'
import { Montserrat } from 'next/font/google'

const montserrat = Montserrat({
  weight:["400","700"],
  subsets:["latin"],
  variable:"--font-montserrat"
})
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} mx-32 my-12`}>{children}</body>
    </html>
  )
}

// https://www.themoviedb.org/settings/api
//a4f63b9cc2393f1106910d00fc65fa56
//https://api.themoviedb.org/3/movie/550?api_key=a4f63b9cc2393f1106910d00fc65fa56
//https://developers.themoviedb.org/3/movies/get-popular-movies
//https://www.youtube.com/watch?v=T63nY70eZF0&ab_channel=developedbyed